from django.urls import path

from . import admin_views as views

urlpatterns = [
    path("content/categories", views.CategoryListCreateView.as_view(), name="admin-categories"),
    path("content/categories/<uuid:category_id>", views.CategoryDetailView.as_view(), name="admin-category"),
    path("content/media", views.MediaListCreateView.as_view(), name="admin-media"),
    path("content/media/<uuid:media_id>", views.MediaDetailView.as_view(), name="admin-media-detail"),
    path("content/articles", views.ArticleListCreateView.as_view(), name="admin-articles"),
    path("content/articles/<uuid:object_id>", views.ArticleDetailView.as_view(), name="admin-article"),
    path("content/articles/<uuid:object_id>/<str:action>", views.ArticlePublishView.as_view(), name="admin-article-publish"),
    path("content/events", views.EventListCreateView.as_view(), name="admin-events"),
    path("content/events/<uuid:object_id>", views.EventDetailView.as_view(), name="admin-event"),
    path("content/events/<uuid:object_id>/<str:action>", views.EventPublishView.as_view(), name="admin-event-publish"),
    path("content/news", views.NewsListCreateView.as_view(), name="admin-news"),
    path("content/news/<uuid:object_id>", views.NewsDetailView.as_view(), name="admin-news-detail"),
    path("content/news/<uuid:object_id>/<str:action>", views.NewsPublishView.as_view(), name="admin-news-publish"),
    path("content/pages", views.PageListCreateView.as_view(), name="admin-pages"),
    path("content/pages/<uuid:object_id>", views.PageDetailView.as_view(), name="admin-page-detail"),
    path("content/pages/<uuid:object_id>/<str:action>", views.PagePublishView.as_view(), name="admin-page-publish"),
    path("content/faqs", views.FAQListCreateView.as_view(), name="admin-faqs"),
    path("content/faqs/reorder", views.FAQReorderView.as_view(), name="admin-faqs-reorder"),
    path("content/faqs/<uuid:faq_id>", views.FAQDetailView.as_view(), name="admin-faq"),
    path("content/homepage", views.HomepageSettingsView.as_view(), name="admin-homepage"),
    path("content/testimonials", views.TestimonialListCreateView.as_view()),
    path("content/testimonials/reorder", views.TestimonialReorderView.as_view()),
    path("content/testimonials/<uuid:object_id>", views.TestimonialDetailView.as_view()),
    path("content/partners", views.PartnerListCreateView.as_view()),
    path("content/partners/reorder", views.PartnerReorderView.as_view()),
    path("content/partners/<uuid:object_id>", views.PartnerDetailView.as_view()),
    path("content/gallery", views.GalleryListCreateView.as_view()),
    path("content/gallery/reorder", views.GalleryReorderView.as_view()),
    path("content/gallery/<uuid:object_id>", views.GalleryDetailView.as_view()),
    path("content/theses", views.ThesisListCreateView.as_view()),
    path("content/theses/reorder", views.ThesisReorderView.as_view()),
    path("content/theses/<uuid:object_id>", views.ThesisDetailView.as_view()),
    path("content/homepage-v2", views.HomepageSettingsV2View.as_view()),
]
