# Generated by Django 6.0.7 on 2026-07-08 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('template', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='email_log_created_d2a0e7_idx'), models.Index(fields=['status', 'template'], name='email_log_status_2f1fbe_idx')],
            },
        ),
    ]
