# Generated by Django 6.0.7 on 2026-07-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('content', '0003_testimonial_thesis_galleryitem_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['sort_order', 'name_ar']},
        ),
        migrations.AddField(
            model_name='program',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset'),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_status',
            field=models.CharField(choices=[('open', 'مفتوح للتسجيل'), ('soon', 'قريبًا'), ('closed', 'مغلق')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
