# Generated by Django 6.0.7 on 2026-07-09 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_faq_sitesetting_page_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('role_ar', models.CharField(blank=True, default='', max_length=100)),
                ('role_en', models.CharField(blank=True, default='', max_length=100)),
                ('quote_ar', models.TextField()),
                ('quote_en', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ar', models.CharField(max_length=300)),
                ('title_en', models.CharField(blank=True, default='', max_length=300)),
                ('researcher_ar', models.CharField(max_length=150)),
                ('researcher_en', models.CharField(blank=True, default='', max_length=150)),
                ('degree', models.CharField(choices=[('masters', 'ماجستير'), ('doctorate', 'دكتوراه')], max_length=12)),
                ('institution_ar', models.CharField(blank=True, default='', max_length=200)),
                ('institution_en', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'theses',
                'db_table': 'theses',
                'ordering': ['sort_order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption_ar', models.CharField(blank=True, default='', max_length=200)),
                ('caption_en', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.mediaasset')),
            ],
            options={
                'db_table': 'gallery_items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, default='', max_length=150)),
                ('url', models.URLField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset')),
            ],
            options={
                'db_table': 'partners',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
