# Generated by Django 6.0.7 on 2026-07-08 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_documents',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('church_other_text', models.CharField(blank=True, default='', max_length=150)),
                ('photo', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality_code', models.CharField(blank=True, default='', max_length=2)),
                ('education_level', models.CharField(blank=True, choices=[('secondary', 'ثانوي'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('doctorate', 'دكتوراه'), ('other', 'أخرى')], default='', max_length=20)),
                ('education_field', models.CharField(blank=True, default='', max_length=120)),
                ('church_service', models.CharField(blank=True, default='', max_length=120)),
                ('confession_father', models.CharField(blank=True, default='', max_length=120)),
                ('bio', models.CharField(blank=True, default='', max_length=500)),
                ('emergency_name', models.CharField(blank=True, default='', max_length=120)),
                ('emergency_relation', models.CharField(blank=True, default='', max_length=60)),
                ('emergency_phone', models.CharField(blank=True, default='', max_length=20)),
                ('completion_pct', models.PositiveSmallIntegerField(default=0)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.church')),
                ('diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.diocese')),
                ('program_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
    ]
